language: ruby
rvm:
- 2.3.0
before_script:
- cp config/database.example.yml config/database.yml
- psql -c 'create database "base_workshops_app_test";' -U postgres # change database name
# by default we use Heroku to run our apps online
# more info how to generate secure api key: https://docs.travis-ci.com/user/deployment/heroku/
# tip: travis encrypt $(heroku auth:token) --add deploy.api_key -r netguru-training/base_workshops_app
deploy:
  provider: heroku
  api_key:
    secure: example_secure_api_key
  run:
  - rake db:migrate
  app: base_workshops_app # change it
  on:
    repo: netguru-training/base_workshops_app # change it
addons:
  postgresql: '9.3'
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
# if you're using Gitter as communication tool, you can integrate it with Travis:
# more info: https://gitter.zendesk.com/hc/en-us/articles/200176722-Integrations
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1234567890
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
